
Sandstorm:
  GedmoTranslatableConnector:
    locale: mul_ZZ
    defaultLocale: mul_ZZ
    translationFallback: false
Neos:
  Flow:
    object:
      excludeClasses:
        gedmo.doctrineextensions:
          - 'Gedmo\\.*'
    persistence:
      doctrine:
        eventListeners:
          Gedmo\Translatable\TranslatableListener:
            events:
              - postLoad
              - postPersist
              - preFlush
              - onFlush
              - loadClassMetadata
            listener: Gedmo\Translatable\TranslatableListener
